export const SELECT_SECTION = 'SELECT_SECTION';
export const PLAYER_ROTATE_SHIP = 'PLAYER_ROTATE_SHIP';
export const PLAYER_PLACE_SHIP = 'PLAYER_PLACE_SHIP';
export const ENEMY_PLACE_ALL_SHIPS = 'ENEMY_PLACE_ALL_SHIPS';
export const PLAYER_HIT = 'PLAYER_HIT';
export const ENEMY_HIT = 'ENEMY_HIT';
